# S3RLINUX Catalyst Configuration
# RAVE ALL NIGHT 🌈💀

storedir="/var/tmp/catalyst"
distdir="/var/cache/distfiles"
jobs=16
load-average=16.0
options=[
    "autoresume",
    "pkgcache",
    "seedcache",
]
